틀린 내용 수정.
logico-philosophical/math-o-matic pull request #62
Opened 2020-11-10 09:17 UTC by erados

2020-11-10 17:39 UTC, logico-philosophical requested changes
환 및 체에 관한 정의를 추가하는 것도 좋은데 먼저 군론에서의 정리들을 증명하는 편이 더 나아 보입니다.

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +$\left(<<\operatorname{group}>>\left(#1,#2\right) \right)$
다시 갖다붙이세요 !!!!!! !! ! !

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +st bin_op_commutative($\ast$ cls f, $A$ cls a) {
`bin_op_associative` 밑에다가 갖다붙이세요

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +$\left(<<\operatorname{abelian group}>>\left(#1,#2\right) \right)$
`\operatorname{abelian group}`의 `abelian`이랑 `group`이 띄어쓰기가 적용되지 않았으니 적용하세요

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +$\left(#1\ <<\text{is left distributive on}>>\ \left(#3,#2\right) \right)$
`* is left distributive over + on A`로 바꾸세요

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +st bin_op_left_distributive($\ast$ cls f, $+$ cls g, $A$ cls a) {
`bin_op_associative` 밑에 갖다붙이세요

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +st bin_op_left_distributive($\ast$ cls f, $+$ cls g, $A$ cls a) {
`\ast`가 더하기도 곱하기도 아닌 일반적 연산을 나타내고 `\cdot`이 곱하기를 나타내도록 할 예정이니 `$\ast$ cls f`를 `$\cdot$ cls f`로 고치세요

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +$\left(<<\operatorname{commutative monoid}>>\left(#1,#2\right) \right)$
`is_monoid` 밑에다가 붙이세요

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +st zero_annihilates($R$ cls r, $\ast$ cls f) {
이거랑 `is_semiring`을 없애고 rng의 정의를 추가하여 `is_ring`의 정의가 rng의 정의에 의존하도록 하세요

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +$\left(<<\operatorname{commutative monoid}>>\left(#1,#2\right) \right)$
역시 띄어쓰기가 안 됨.

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +st is_ring($R$ cls r, $+$ cls g, $\ast$ cls f) {
`$\ast$` 말고 `$\cdot$`으로 바꾸세요

2020-11-10 17:39 UTC, logico-philosophical commented on math/abstract_algebra.math
> +$\left(<<\operatorname{commutative ring}>>\left(#1,#2,#3\right) \right)$
역시 띄어쓰기 안됨 !!!

2020-11-10 23:39 UTC, erados commented on math/abstract_algebra.math
> +st bin_op_left_distributive($\ast$ cls f, $+$ cls g, $A$ cls a) {
저도 일반적인 연산을 나타낸 건데요?

2020-11-10 23:42 UTC, erados commented
> 환 및 체에 관한 정의를 추가하는 것도 좋은데 먼저 군론에서의 정리들을 증명하는 편이 더 나아 보입니다.

그러도록 하죠

2020-11-11 00:25 UTC, logico-philosophical commented on math/abstract_algebra.math
> +st bin_op_left_distributive($\ast$ cls f, $+$ cls g, $A$ cls a) {
`$\ast$`가 일반적 연산을 나타낸다 한 것은 additive인지 multiplicative인지 모르는 연산을 나타낸다는 뜻이고 이 정의에서는 `f`가 multiplicative 하므로 `$\cdot$`을 쓰겠다는 것임. https://en.wikipedia.org/wiki/Abelian_group#Notation 참조

2020-11-11 00:55 UTC, erados commented on math/abstract_algebra.math
> +$\left(#1\ <<\text{is left distributive on}>>\ \left(#3,#2\right) \right)$
그게 쉽지 않네요

2020-11-11 01:01 UTC, erados commented on math/abstract_algebra.math
> +st bin_op_left_distributive($\ast$ cls f, $+$ cls g, $A$ cls a) {
그건 아벨 군에 한정했을 때 이야기 아닌가 벡터 공간 넘어가고 선형 변환나오고 행렬곱 나와도 저거 그대로 쓸 수 있나? 일단 알았다.

2020-11-11 01:08 UTC, logico-philosophical commented on math/abstract_algebra.math
> +st bin_op_left_distributive($\ast$ cls f, $+$ cls g, $A$ cls a) {
벡터공간에서의 스칼라배 연산은 F×V 상에서 이루어지므로 여기서 말하는 이항연산이 아니다.

2020-11-11 01:19 UTC, erados commented
수정함.

2020-11-11 01:19 UTC, closed without merging

2020-11-11 01:26 UTC, erados commented on math/abstract_algebra.math
> +st bin_op_left_distributive($\ast$ cls f, $+$ cls g, $A$ cls a) {
ㅇㅈ합니다.