Adding subgroup
logico-philosophical/math-o-matic pull request #69
Opened 2020-11-16 07:24 UTC by erados

I think this is good.

2020-11-16 07:34 UTC, logico-philosophical commented
nah

2020-11-16 07:57 UTC, erados commented
사람들 보니까 PR 하나에 계속 commit 추가하던데 왜 계속 닫음.

2020-11-16 07:58 UTC, erados commented
PR 열어두고 commit 추가 하면 안되겠니

2020-11-16 10:57 UTC, erados commented
comment needed

2020-11-16 20:23 UTC, logico-philosophical requested changes
부분군에 관한 다음의 기본적 사실을 증명해 보라. 정의를 예쁘게 만드는 것의 중요성을 알 수 있을 것이다.

> A subset *H* of the group *G* is a subgroup of *G* if and only if it is nonempty and closed under products and inverses. (https://en.wikipedia.org/wiki/Subgroup#Basic_properties_of_subgroups)

Fraleigh 7판(ISBN 978-1-29202-496-7) 정리 5.14다. 책에서는 nonempty 조건 대신 *e* ∈ *H*를 요구한다.

2020-11-16 20:23 UTC, logico-philosophical commented on math/function.math
> +}
- 설명에 영어 이름도 써 주면 좋겠다.
- 설명이 마침표로 끝났으면 좋겠다.
- `\upharpoonright`이 클릭 가능하면 좋겠다.

2020-11-16 20:26 UTC, logico-philosophical commented
대충 https://chris.beams.io/posts/git-commit/ 에서의 다음과 같은 규칙을 지켜서 커밋 메시지나 PR의 제목을 작성하자.

1. Separate subject from body with a blank line
1. Limit the subject line to 50 characters
1. Capitalize the subject line
1. Do not end the subject line with a period
1. Use the imperative mood in the subject line
1. Wrap the body at 72 characters
1. Use the body to explain what and why vs. how

2020-11-17 01:50 UTC, erados commented on math/abstract_algebra.math
> +}
`is_group(G, f)` 는 증명을 적을 때 이미 고려해서 필요 없는 건지?

2020-11-17 04:10 UTC, logico-philosophical commented on math/abstract_algebra.math
> +}
맞음 ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ

2020-11-17 18:55 UTC, logico-philosophical requested changes
ㅇㅇ

2020-11-17 18:55 UTC, logico-philosophical commented on math/abstract_algebra.math
> +	}),
안타깝게도 *e* ∈ *H*는 *G*의 항등원이 *H*에 포함된다는 뜻이었다. 그러므로 `in(identity_element(g, f), h)`라 하는 것이 맞을 것이다.

2020-11-17 18:55 UTC, logico-philosophical commented on math/abstract_algebra.math
> +	}) |-
이것도 비슷하게 (*G*, \*)에서의 *a*의 역원이 *H*에 속한다고 하는 것이 맞을 것이다.

2020-11-17 18:55 UTC, logico-philosophical commented on math/abstract_algebra.math
> +$\left(#1<<\leq>>#2\right)$
현재 모든 인자가 수식 상에 드러나도록 하고 있으므로 `{<<\leq>>}_{#3}`이라 하는 것이 좋을 것 같다.

2020-11-28 02:21 UTC, erados commented
Repo removed due to Conflict.
Successive PR on #76.

2020-11-28 03:12 UTC, closed without merging